#!/usr/bin/env bash
# Does the following:
#   Create a file /var/run/myscript.pid containing the script PID
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT
#   Deletes the file /var/run/myscript.pid and terminates upon
#+  receiving a SIGQUIT or SIGTERM

true=0
echo $BASHPID > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit 0;' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit 0;' SIGQUIT
while [ $true ]; do
	echo 'To infinity and beyond'
	sleep 2
done;
