#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely, pause 2
# 	seconds between iterations

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
	echo To infinity and beyond
	sleep 2
done
