#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# 	display hours from 0 to 12
# 	display minutes from 1 to 59

h=0
while ((h < 13 ))
do
	echo "Hour: $h"
	((h++))

	m=1
	while ((m < 60 ))
	do
		echo "$m"
		((m++))
	done
done
