#!/usr/bin/env bash
# Bash script that displays:
#  	The content of the current directory
#  	In a list format
#  	Where only the part of the name after the first dash is displayed (refer to the example)

for f in *
do
	echo "$f" | #Pipe output redirection to cut input command
	cut -d '-' -f2 # Use - as delimiter instead of TAB, only show second part of
	#	- split
done
